# Generated by Django 6.0 on 2026-01-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cliente_produto'),
        ('home', '0003_produto'),
    ]

    operations = [
    ]
