# Generated by Django 6.0 on 2026-02-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_pedido_forma_pagamento_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[('a_vista', 'À Vista'), ('parcelado', 'Parcelado')], default='a_vista', max_length=20),
        ),
    ]
